// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOOb5Xw00Jnn8Viwqa-bMwazmLRHYGgvA',
    appId: '1:712229651352:web:1b2533f0a7ff6e70e1e1ed',
    messagingSenderId: '712229651352',
    projectId: 'brew-crew-tutorial-pp',
    authDomain: 'brew-crew-tutorial-pp.firebaseapp.com',
    storageBucket: 'brew-crew-tutorial-pp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBruwlgFT12uZKRJIKBlTMSkXXy3YiVLdU',
    appId: '1:712229651352:android:2a0d4a1d7c301345e1e1ed',
    messagingSenderId: '712229651352',
    projectId: 'brew-crew-tutorial-pp',
    storageBucket: 'brew-crew-tutorial-pp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC93WrgOPDxv9S-b6pVC-mFEmEhhvSRcCA',
    appId: '1:712229651352:ios:67d9f66597077f33e1e1ed',
    messagingSenderId: '712229651352',
    projectId: 'brew-crew-tutorial-pp',
    storageBucket: 'brew-crew-tutorial-pp.appspot.com',
    iosClientId: '712229651352-67jbns8n9hjgtms3c8lbkb51shq9dr9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC93WrgOPDxv9S-b6pVC-mFEmEhhvSRcCA',
    appId: '1:712229651352:ios:67d9f66597077f33e1e1ed',
    messagingSenderId: '712229651352',
    projectId: 'brew-crew-tutorial-pp',
    storageBucket: 'brew-crew-tutorial-pp.appspot.com',
    iosClientId: '712229651352-67jbns8n9hjgtms3c8lbkb51shq9dr9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
